### ISSUE TITLE
LOG4CPLUS_LIB  NOTFOUND.

### ISSUE THREAD

**Issue by zspking** [DavidLiuXh/kuafu#1]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LOG4CPLUS_LIB
    linked by target "kuafu" in directory /home/zsp/src/test/Interview/interview-examples/FSM/kuafu-master

-- Configuring incomplete, errors occurred!

但是其实我已经另外下载了log4cplus源码编译安装成功了

**Comment by DavidLiuXh** [comment]
@zspking 你可以 改一下 CMakeLists.txt中的 FIND_LIBRARY(LOG4CPLUS_LIB NAMES log4cplus PATHS /usr/local/lib /usr/lib PATH_SUFFIXES so)
